### ISSUE TITLE
Files without title, artist, album are not added to library

### ISSUE THREAD

**Issue by stigsell** [Mpmart08/MusicPlayer#24]
`<song>
            <id>81</id>
            <title/>
            <artist/>
            <album/>
            <length>342</length>
            <trackNumber>0</trackNumber>
            <discNumber>0</discNumber>
            <playCount>0</playCount>
            <playDate>2016-07-19T22:01:24.268</playDate>
            <location>/Users/nick/Dropbox/Music/Bon Iver/Bon Iver Eaux Claires Concert/Blindsided.mp3</location>
        </song>`

I have many song files that are like this one. They don't have any metadata from iTunes or other media players. The MusicPlayer app puts them in the library.xml but they do not appear in the GUI to play

**Comment by Mpmart08** [comment]
This is a weird problem to solve because I think alot of people have untagged music which makes it difficult to organize their music.

Is there an Unknown Artist in your list of Artists? I recreated your scenario and took a screenshot of the results:

![image](https://cloud.githubusercontent.com/assets/9096552/17079146/4efc26d0-50d5-11e6-8996-bf16aeb1cfea.png)
